FROM python:3.12

# Définir le dossier de travail
WORKDIR /app

# Copier les fichiers du projet
COPY  . .

WORKDIR ~/
COPY .streamlit/ .streamlit/

WORKDIR /app

# Installer les dépendances
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirement.txt

# Exposer le port Streamlit
EXPOSE 8501

# Lancer l'application Streamlit
CMD ["streamlit", "run", "app.py"]
